# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-06 16:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mapa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporte',
            name='estado',
            field=models.BooleanField(default=False, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='reporte',
            name='curso',
            field=models.IntegerField(blank=True, default=0, help_text='Curso académico', null=True, verbose_name='Curso académico'),
        ),
        migrations.AlterField(
            model_name='reporte',
            name='descripcion',
            field=models.TextField(help_text='Describe el problema', max_length=100000, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='reporte',
            name='email',
            field=models.EmailField(blank=True, help_text='Indica un correo electrónico si deseas que nos pongamos en contacto contigo', max_length=254, null=True, verbose_name='Correo electrónico'),
        ),
        migrations.AlterField(
            model_name='reporte',
            name='universidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reportes', to='tasas.Universidad', verbose_name='Universidad'),
        ),
    ]
