version: '3'
services:
  app:
    build:
      context: .
    ports:
      - 8000:8000
    volumes:
      - .:/root
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      - rendervariations
  rendervariations:
    build:
      context: .
    volumes:
      - ./media:/root/media
      - ./static:/root/static
    command: sh -c "python3 manage.py rendervariations 'tasas.universidad.logo' && python3 manage.py collectstatic --noinput"
    environment:
      - PYTHONUNBUFFERED=1
