# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-27 16:42
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tasa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.IntegerField(choices=[(0, 'Precio por crédito'), (1, 'Pago único'), (2, 'Misceláneo')], help_text='Tipo de tasa')),
                ('tipo_titulacion', models.IntegerField(choices=[(0, 'Grado'), (0, 'Máster')], help_text='Tipo de titulación (grado/máster)')),
                ('curso', models.IntegerField(help_text='Curso académico en el que esta tasa se aplica', validators=django.core.validators.RegexValidator(regex='^\\d{4}$'))),
                ('url', models.URLField(blank=True, help_text='URL del documento oficial')),
                ('tasa_global', models.FloatField(blank=True, help_text='Tasa global', null=True)),
                ('descripcion', models.TextField(blank=True, help_text='Texto informativo sobre la tasa', max_length=500, null=True)),
                ('tasas1', models.FloatField(blank=True, help_text='Primera convocatoria', null=True)),
                ('tasas2', models.FloatField(blank=True, help_text='Segunda convocatoria', null=True)),
                ('tasas3', models.FloatField(blank=True, help_text='Tercera convocatoria', null=True)),
                ('tasas4', models.FloatField(blank=True, help_text='Cuarta convocatoria', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Universidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('siglas', models.CharField(help_text='Siglas de la universidad', max_length=20, unique=True)),
                ('nombre', models.CharField(help_text='Nombre de la universidad', max_length=200)),
                ('tipo', models.IntegerField(choices=[(0, 'Pública'), (1, 'Privada')], help_text='Tipo de centro (público/privado)')),
                ('centro', models.CharField(help_text='Nombre del centro', max_length=200)),
                ('provincia', models.CharField(choices=[('Alava', 'Álava'), ('Albacete', 'Albacete'), ('Alicante', 'Alicante'), ('Almeria', 'Almería'), ('Asturias', 'Asturias'), ('Avila', 'Ávila'), ('Badajoz', 'Badajoz'), ('Balearas', 'Baleares'), ('Barcelona', 'Barcelona'), ('Burgos', 'Burgos'), ('Caceres', 'Cáceres'), ('Cadiz', 'Cádiz'), ('Cantabria', 'Cantabria'), ('Castellon', 'Castellón'), ('Ceuta', 'Ceuta'), ('Ciudad Real', 'Ciudad Real'), ('Cordoba', 'Córdoba'), ('Cuenca', 'Cuenca'), ('Gerona', 'Gerona'), ('Granada', 'Granada'), ('Guadalajara', 'Guadalajara'), ('Gipuzkoa', 'Gipuzkoa'), ('Huelva', 'Huelva'), ('Huesca', 'Huesca'), ('Jaen', 'Jaén'), ('La Coruna', 'La Coruña'), ('La Rioja', 'La Rioja'), ('Las Palmas', 'Las Palmas'), ('Leon', 'León'), ('Lerida', 'Lérida'), ('Lugo', 'Lugo'), ('Madrid', 'Madrid'), ('Malaga', 'Málaga'), ('Melilla', 'Melilla'), ('Murcia', 'Murcia'), ('Navarra', 'Navarra'), ('Orense', 'Orense'), ('Palencia', 'Palencia'), ('Pontevedra', 'Pontevedra'), ('Salamanca', 'Salamanca'), ('Santa Cruz de Tenerife', 'Santa Cruz de Tenerife'), ('Segovia', 'Segovia'), ('Sevilla', 'Sevilla'), ('Soria', 'Soria'), ('Tarragona', 'Tarragona'), ('Teruel', 'Teruel'), ('Toledo', 'Toledo'), ('Valencia', 'Valencia'), ('Valladolid', 'Valladolid'), ('Bizkaia', 'Bizkaia'), ('Zamora', 'Zamora'), ('Zaragoza', 'Zaragoza')], help_text='Provincia', max_length=50)),
                ('logo', models.ImageField(blank=True, help_text='Escudo de la universidad', null=True, upload_to='escudos')),
                ('url', models.URLField(blank=True, help_text='URL del centro', max_length=300)),
            ],
        ),
        migrations.AddField(
            model_name='tasa',
            name='universidad',
            field=models.ForeignKey(help_text='Universidad asociada a esta tasa', on_delete=django.db.models.deletion.CASCADE, related_name='tasas', related_query_name='tasa', to='tasas.Universidad'),
        ),
    ]
