# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-27 18:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='universidad',
            name='campus',
            field=models.CharField(blank=True, help_text='Nombre del campus', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='universidad',
            name='url',
            field=models.URLField(blank=True, help_text='URL del centro', max_length=300, null=True),
        ),
    ]
