# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-27 19:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasas', '0002_auto_20160227_1902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='universidad',
            name='centro',
            field=models.CharField(blank=True, help_text='Nombre del centro', max_length=200, null=True),
        ),
    ]
