# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-28 13:21
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import tasas.models


class Migration(migrations.Migration):

    dependencies = [
        ('tasas', '0003_auto_20160227_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasa',
            name='curso',
            field=models.IntegerField(help_text='Curso académico en el que esta tasa se aplica', validators=[django.core.validators.RegexValidator(regex='^\\d{4}$')]),
        ),
        migrations.AlterField(
            model_name='tasa',
            name='tasas1',
            field=models.FloatField(blank=True, help_text='Primera convocatoria', null=True, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
        migrations.AlterField(
            model_name='tasa',
            name='tasas2',
            field=models.FloatField(blank=True, help_text='Segunda convocatoria', null=True, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
        migrations.AlterField(
            model_name='tasa',
            name='tasas3',
            field=models.FloatField(blank=True, help_text='Tercera convocatoria', null=True, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
        migrations.AlterField(
            model_name='tasa',
            name='tasas4',
            field=models.FloatField(blank=True, help_text='Cuarta convocatoria', null=True, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
        migrations.AlterField(
            model_name='tasa',
            name='tipo_titulacion',
            field=models.IntegerField(choices=[(0, 'Grado'), (1, 'Máster')], help_text='Tipo de titulación (grado/máster)'),
        ),
        migrations.AlterField(
            model_name='tasa',
            name='universidad',
            field=models.ForeignKey(blank=True, help_text='Universidad asociada a esta tasa', on_delete=django.db.models.deletion.CASCADE, related_name='tasas', related_query_name='tasa', to='tasas.Universidad'),
        ),
        migrations.AlterField(
            model_name='tasa',
            name='url',
            field=models.URLField(help_text='URL del documento oficial'),
        ),
    ]
