# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-04 17:25
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('tasas', '0009_auto_20160301_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='universidad',
            name='logo',
            field=stdimage.models.StdImageField(blank=True, help_text='Escudo de la universidad', null=True, upload_to='escudos'),
        ),
        migrations.AlterField(
            model_name='universidad',
            name='siglas',
            field=models.CharField(help_text='Siglas de la universidad', max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='Las siglas de la universidad solo pueden contener letras y guiones (-)', regex='[A-Za-z\\-]+')]),
        ),
    ]
