# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-04 17:26
from __future__ import unicode_literals

from django.db import migrations
import stdimage.models
import stdimage.validators


class Migration(migrations.Migration):

    dependencies = [
        ('tasas', '0010_auto_20160304_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='universidad',
            name='logo',
            field=stdimage.models.StdImageField(blank=True, help_text='Escudo de la universidad', null=True, upload_to='escudos', validators=[stdimage.validators.MinSizeValidator(100, 100)]),
        ),
    ]
