# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-06 14:07
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import tasas.models


class Migration(migrations.Migration):

    dependencies = [
        ('tasas', '0012_auto_20160306_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasa',
            name='curso',
            field=models.IntegerField(choices=[(2011, '2011/2012'), (2012, '2012/2013'), (2013, '2013/2014'), (2014, '2014/2015'), (2015, '2015/2016'), (2016, '2016/2017')], help_text='Curso académico en el que esta tasa se aplica', validators=[django.core.validators.RegexValidator(regex='^\\d{4}$')]),
        ),
    ]
