# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-06 16:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasas', '0013_auto_20160306_1507'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tasa',
            unique_together=set([('universidad', 'curso', 'tipo_titulacion')]),
        ),
    ]
