# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2018-05-24 14:06
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import tasas.models


class Migration(migrations.Migration):

    dependencies = [
        ('tasas', '0014_auto_20160306_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasa',
            name='curso',
            field=models.IntegerField(choices=[(2011, '2011/2012'), (2012, '2012/2013'), (2013, '2013/2014'), (2014, '2014/2015'), (2015, '2015/2016'), (2016, '2016/2017'), (2017, '2017/2018'), (2018, '2018/2019')], help_text='Curso académico en el que esta tasa se aplica', validators=[django.core.validators.RegexValidator(regex='^\\d{4}$'), tasas.models.CursoValidator()]),
        ),
        migrations.AlterField(
            model_name='universidad',
            name='siglas',
            field=models.CharField(help_text='Siglas de la universidad', max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='Las siglas de la universidad solo pueden contener letras y guiones (-)', regex='^[a-z\\-]+$')]),
        ),
    ]
