# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-04 14:50
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import tasas.models


class Migration(migrations.Migration):

    dependencies = [
        ('tasas', '0014_auto_20160306_1723'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anno', models.IntegerField(unique=True, verbose_name='Año')),
                ('activo', models.IntegerField(default=True)),
            ],
        ),
        migrations.AlterField(
            model_name='tasa',
            name='curso',
            field=models.IntegerField(choices=[(2011, '2011/2012'), (2012, '2012/2013'), (2013, '2013/2014'), (2014, '2014/2015'), (2015, '2015/2016'), (2016, '2016/2017'), (2017, '2017/2018')], help_text='Curso académico en el que esta tasa se aplica', validators=[django.core.validators.RegexValidator(regex='^\\d{4}$')]),
        ),
    ]
