# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-04 14:53
from __future__ import unicode_literals

from django.db import migrations, models
import tasas.models


class Migration(migrations.Migration):

    dependencies = [
        ('tasas', '0015_auto_20160904_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='curso',
            name='anno',
            field=models.IntegerField(unique=True,  verbose_name='Año'),
        ),
    ]
