# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-04 14:55
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import tasas.models


class Migration(migrations.Migration):

    dependencies = [
        ('tasas', '0016_auto_20160904_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='anno',
            field=models.IntegerField(unique=True, validators=[django.core.validators.RegexValidator(regex='^\\d{4}$'), tasas.models.CursoValidator()], verbose_name='Año'),
        ),
        migrations.AlterField(
            model_name='tasa',
            name='curso',
            field=models.ForeignKey(help_text='Curso académico en el que esta tasa se aplica', on_delete=django.db.models.deletion.CASCADE, to='tasas.Curso'),
        ),
    ]
