# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-11-02 10:03
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasas', '0019_curso_actual'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curso',
            name='id',
        ),
        migrations.AlterField(
            model_name='curso',
            name='anno',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True, validators=[django.core.validators.RegexValidator(regex='^\\d{4}$')], verbose_name='Año'),
        ),
    ]
