# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2018-01-18 18:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasas', '0020_auto_20161102_1103'),
    ]

    operations = [
        migrations.AddField(
            model_name='universidad',
            name='activa',
            field=models.BooleanField(default=True),
        ),
    ]
