PROVINCIAS = (
    ("Alava", "Álava"),
    ("Albacete", "Albacete"),
    ("Alicante", "Alicante"),
    ("Almeria", "Almería"),
    ("Asturias", "Asturias"),
    ("Avila", "Ávila"),
    ("Badajoz", "Badajoz"),
    ("Baleares", "Baleares"),
    ("Barcelona", "Barcelona"),
    ("Burgos", "Burgos"),
    ("Caceres", "Cáceres"),
    ("Cadiz", "Cádiz"),
    ("Cantabria", "Cantabria"),
    ("Castellon", "Castellón"),
    ("Ceuta", "Ceuta"),
    ("Ciudad Real", "Ciudad Real"),
    ("Cordoba", "Córdoba"),
    ("Cuenca", "Cuenca"),
    ("Gerona", "Gerona"),
    ("Granada", "Granada"),
    ("Guadalajara", "Guadalajara"),
    ("Gipuzkoa", "Gipuzkoa"),
    ("Huelva", "Huelva"),
    ("Huesca", "Huesca"),
    ("Jaen", "Jaén"),
    ("La Coruna", "La Coruña"),
    ("La Rioja", "La Rioja"),
    ("Las Palmas", "Las Palmas"),
    ("Leon", "León"),
    ("Lerida", "Lérida"),
    ("Lugo", "Lugo"),
    ("Madrid", "Madrid"),
    ("Malaga", "Málaga"),
    ("Melilla", "Melilla"),
    ("Murcia", "Murcia"),
    ("Navarra", "Navarra"),
    ("Orense", "Orense"),
    ("Palencia", "Palencia"),
    ("Pontevedra", "Pontevedra"),
    ("Salamanca", "Salamanca"),
    ("Santa Cruz de Tenerife", "Santa Cruz de Tenerife"),
    ("Segovia", "Segovia"),
    ("Sevilla", "Sevilla"),
    ("Soria", "Soria"),
    ("Tarragona", "Tarragona"),
    ("Teruel", "Teruel"),
    ("Toledo", "Toledo"),
    ("Valencia", "Valencia"),
    ("Valladolid", "Valladolid"),
    ("Bizkaia", "Bizkaia"),
    ("Zamora", "Zamora"),
    ("Zaragoza", "Zaragoza")
)
